# Generated by Django 6.0.7 on 2026-07-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='preferredLanguage',
            new_name='preferred_language',
        ),
    ]
