# Generated by Django 6.0.7 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
