# Generated by Django 6.0.4 on 2026-08-19 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medicaldocument_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.CharField(default='Tablet', max_length=50)),
                ('dosage', models.CharField(default='1 tablet', max_length=100)),
                ('frequency', models.CharField(default='Twice daily', max_length=100)),
                ('timing', models.CharField(default='After meals', max_length=100)),
                ('duration_days', models.IntegerField(default=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='patients.medicaldocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('scheduled_datetime', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DUE', 'Due'), ('TAKEN', 'Taken')], db_index=True, default='PENDING', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='patients.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_doses', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
                'unique_together': {('patient', 'medication', 'scheduled_datetime')},
            },
        ),
    ]
