# Generated by Django 6.0.4 on 2026-08-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medication_scheduleddose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MEDICATION_DUE', 'Medication Due')], default='MEDICATION_DUE', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_notifications', to='patients.patient')),
                ('scheduled_dose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='patients.scheduleddose')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
