# Generated by Django 6.0.4 on 2026-08-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_medicationremindernotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PROCESSED', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('medical_report', 'Medical Report'), ('discharge_summary', 'Discharge Summary'), ('lab_test', 'Lab Test Report'), ('other', 'Other Medical Document')], default='prescription', max_length=50),
        ),
    ]
