# Generated by Django 6.0.4 on 2026-08-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_medicaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PRESCRIPTION_UPLOADED', 'Prescription Uploaded'), ('MEDICATION_REMINDER_CREATED', 'Reminder Created'), ('MEDICATION_REMINDER_UPDATED', 'Reminder Updated'), ('MEDICATION_REMINDER_DELETED', 'Reminder Deleted'), ('MEDICATION_DOSE_DUE', 'Medication Due'), ('MEDICATION_DOSE_TAKEN', 'Medication Taken')], default='MEDICATION_REMINDER_CREATED', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='patients.patient')),
                ('scheduled_dose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.scheduleddose')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MedicationReminderNotification',
        ),
    ]
