# Generated by Django 6.0.4 on 2026-08-19 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_medication_options_appnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(choices=[('PRESCRIPTION_UPLOADED', 'Prescription Uploaded'), ('MEDICATION_REMINDER_CREATED', 'Reminder Created'), ('MEDICATION_REMINDER_UPDATED', 'Reminder Updated'), ('MEDICATION_REMINDER_DELETED', 'Reminder Deleted'), ('MEDICATION_DOSE_DUE', 'Medication Due'), ('MEDICATION_DOSE_MISSED', 'Medication Missed'), ('MEDICATION_DOSE_TAKEN', 'Medication Taken')], default='MEDICATION_REMINDER_CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='scheduleddose',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DUE', 'Due'), ('TAKEN', 'Taken'), ('MISSED', 'Missed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
